spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/department
    username: root
    password: myadmin123
    driverClassName: com.mysql.jdbc.Driver
  message: hello world, Patrick, Demo spring cloud bus with actuator /busrefresh updated 3
  

eureka:
  instance:
    client:
      serverUrl:
        defaultZone: http://localhost:8761/
server:
  port: 8082
management:
  endpoints:
    web:
      exposure:
        include: "*"
management.endpoint.health.show-details: always
