
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/bankapp
    username: root
    password: myadmin123
    driverClassName: com.mysql.jdbc.Driver

server:
  port: 8081

eureka:
  instance:
    client:
      serverUrl:
        defaultZone: http://localhost:8761/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
management.endpoint.health.show-details: always
info:
  app:
    name: "Spring boot Restfull Web services"
    description: "Employee Service"
    version: "1.0.0"
